### ISSUE TITLE
feat: Eliminate Requirement for Task Model to be Public

### ISSUE THREAD

**Issue by rlabusiness** [open-webui/open-webui#14172]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.

### Problem Description

CONTEXT:
When upgrading beyond 0.6.5, I noticed a requirement that the task model must be public. I now get an error that says “This model is not publicly available. Please select another model.” Prior to this, I could select any task model and it would work for all users without having to share the model with them.

This creates a problem for me because my use case requires offering a limited set of highly curated and customized models with very tailored system prompts and parameters, and not allowing access to other models.

### Desired Solution you'd like

Either (1) restore the prior functionality that doesn’t require the task model to be public in order to be used behind the scenes for all of the tasks it does, or (2) allow the task models (even though public) to be hidden from all users.

I’d prefer (1) because it makes a lot more sense to me that the system has access to all models for whatever tasks it needs without having to make them public and expose the internal task model to everyone, instead of requiring a task model to be made public then hiding it from the public - that’s a contradiction that’s way more confusing than the system simply being able to use it.

### Alternatives Considered

I can’t find any alternatives that are built in to the system now. I don’t want to maintain a separate code base to solve this issue.

### Additional Context

Just FYI in case this matters - I prefer to use a model I’ve created in the workspace based on the task model I’ve created in ollama which I set to keepalive=forever so it’s always ready. I noticed in 0.6.9 that these workspace models disappeared from the task dropdown list, but they’ve returned again in 0.6.10, so I assume that was just a bug that’s now been resolved.

**Comment by Ithanil** [comment]
I think you're wrong on that a private model worked as task model for users prior to 0.6.5. In my opinion it didn't, for example such users wouldn't get chat titles generated. Of course I might be wrong on the timing though and that was after 0.6.5.

That's why I proposed the following PR: https://github.com/open-webui/open-webui/pull/12039, which was not accepted. Instead, it was proposed to open the issue https://github.com/open-webui/open-webui/issues/12080, which was then addressed in https://github.com/open-webui/open-webui/commit/def5444ea3d1bfba18f808991e471d52eda3b78e .

Thus, what you should do is *hide* the task model, just as you propose in 2).

**Comment by tjbck** [comment]
You can hide model instead.

**Comment by rlabusiness** [comment]
@Ithanil

Ah - I got it now. Thanks for the help. I had actually been trying to hide the model exactly like the linked issue described, but I didn't relaize there was a "hide" feature separate from "disable". Disabling the model obviously didn't fix things.
 
It still doesn't seem to have been this way in the past (I have a bunch of threads in a more limited account that never had access to this task model, and since I've been running 0.6.5 for a while, it appeared to be working). I tested 0.6.5 and confirmed its behavior was the same as 0.6.10.
 
The first version this server ran was 0.5.7, so it might have been different back then? Or, I suppose it is possible that as i've been playing around and configuring things, I selected a model that was accessible to the limited user as a task model, so I can't totally eliminate that possibility.
 
Note that these tests were done directly with an Ollama model that's available on all of my Ollama servers. In practice, i prefer to create a Workspace model (based on that Ollama model) in Open-WebUI and assign that as the task model so that I have easy access to its parameters.

I'll separately request that the "hide" solution support Workspace models, too.
