### ISSUE TITLE
release new version with bundled ollama 0.11 to support gpt-oss models

### ISSUE THREAD

**Issue by sbe-arg** [open-webui/open-webui#16306]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

0.6.18

### Operating System

fedora

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

Current version of ollama needs updating to support gpt-oss

https://ollama.com/library/gpt-oss

### Actual Behavior

n/a

### Steps to Reproduce

n/a

### Logs & Screenshots

n/a

### Additional Information

n/a

**Comment by sbe-arg** [comment]
FYI in the meantime I'm just updating ollama on container start doing XD

```
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - open-webui_data:/app/backend/data
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: >
      sh -c "curl -fsSL https://ollama.com/install.sh | sh && exec bash start.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

**Comment by rgaricano** [comment]
some issues for this model fixed in ollama [v0.11.2](https://github.com/ollama/ollama/releases/tag/v0.11.2) and more in pre-release [v0.11.3](https://github.com/ollama/ollama/releases/tag/v0.11.3)

**Comment by gaby** [comment]
v0.11.3 has been released

**Comment by marabgol** [comment]
the issue 'issue:500 : template' is resolved , thanks

**Comment by gaby** [comment]
This is only resolved if installing stuff manually. The latest docker image from OpenWebUI has the same bug

**Comment by gaby** [comment]
This can be closed, release was done today

**Comment by Werewolfke** [comment]
<img width="386" height="282" alt="Image" src="https://github.com/user-attachments/assets/510801e8-9746-4876-a91b-bbd52eeef1ec" />

Version v0.6.21 still not working to pull gpt-oss
Docker webui and ollama together, cpu only.
